PATH_TO_DBS = '../../_data/'

DRIVE_ROOT_ID = '17tvogD2WnmudB-MqnAdxnNCC7CtZS-Gm'
DRIVE_OUTPUT = PATH_TO_DBS + 'autoGenerated/notesTree.yml'
DRIVE_PDF_URL = 'https://drive.google.com/file/d/'
DRIVE_FOLDER_URL = 'https://drive.google.com/drive/u/2/folders/'

TREE_FILE = PATH_TO_DBS + 'autoGenerated/notesTree.yml'
DB_FILES = {
        'subjects': {
            'aliases': PATH_TO_DBS + 'subjects.yml',
            'newNames': PATH_TO_DBS + 'autoGenerated/newSubjects.yml',
            'list': PATH_TO_DBS + 'autoGenerated/subjectsList.yml',
            },
        'lecturers': {
            'aliases': PATH_TO_DBS + 'lecturers.yml',
            'newNames': PATH_TO_DBS + 'autoGenerated/newLecturers.yml',
            },
        'notesList': PATH_TO_DBS + 'autoGenerated/notesList.yml',
        }
LOG_FILE = PATH_TO_DBS + 'autoGenerated/badNamedNotesAndSubjects.log'

ALIASES_STR_BEGIN = 4
ALIASES_STR_END = -3
