import yaml
from updateLecturersAndSubjects import getDatabase 

def handleWantToAddInput(name):
    print('whant to add "' + name + '" in subjects database? [y/n]')
    while True:
        ans = input()
        if ans == 'y' or ans == 'n':
            break
    return ans

def handleAliasesInput():
    print('list aliases, separated by comma:')
    aliases = input()
    print('Do you whant to add "' + aliases +'"? [y(es)/r(etry)/n(ot)]')

    while True:
        ans = input()
        if ans == 'y' or ans == 'n' or ans == 'r':
            break
    if ans == r: return handleAliasesInput()
    else: return {'ans': ans, 'aliases': aliases}


def main():
    for name in getDatabase('../_data/autoGenerated/newSubjects.yml'):
        ans = handleWantToAddInput(name)
        if ans == 'n': continue
        ans = handleAliasesInput()
        if ans['ans'] == 'n': continue

        newAliases = '|' + name + '|' + ('|').join(ans['aliases'].split(',')) + '|'
        with open('../_data/subjects.yml', 'a') as f:
            print(newAliases)

if __name__ == "__main__":
    main()

