name: Updating Notes Database
on: 
  schedule:
    - cron: "0 0 * * *"


jobs: 
  Updating-Notes-Database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
     
      - name: Pull changes form Google Drive
        run: |
          cd assets
          echo ${{ secrets.GOOGLE_API_KEY }} > apiKey.txt
          make
          rm apiKey.txt
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions

