name: Updating Notes Database
on: [push]

jobs: 
  Updating-Notes-Database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
     
      - name: Update source code
        run: cd assets && make testActions && ls
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions

